Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/flow.py", line 9, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 552, in run
    run.runEclipse()
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 388, in runEclipse
    raise subprocess.CalledProcessError(return_code, command)
subprocess.CalledProcessError: Command '['/usr/bin/flow', 'SPE3']' returned non-zero exit status 1.
